### ISSUE TITLE
Im experiencing issues with my mom

### ISSUE THREAD

**Issue by smokeytube** [d1snin/pulseq#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**
handling long-term activity when simple single activities are supported.

**Screenshots**
![image](https://user-images.githubusercontent.com/67290867/146686800-0ade5a57-570f-449a-9074-4ff12724ca69.png)
![image](https://user-images.githubusercontent.com/67290867/146686805-a49d7f21-9ea2-4bae-b804-c197779ab8e1.png)
![image](https://user-images.githubusercontent.com/67290867/146686811-29a824d3-d46b-4a86-80d2-7914eac61851.png)
![image](https://user-images.githubusercontent.com/67290867/146686816-a48ad994-b0ec-41f6-818e-bd47b8624341.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 4

**Smartphone (please complete the following information):**
 - Device: Google pixel 4a
 - OS: Android??
 - Browser Chrome
 - Version 0.76

**Comment by d1snin** [comment]
Thank you for the report!! Your issue depends on #96

**Comment by smokeytube** [comment]
You're welcome. Hopefully this issue can be resolved quickly. Happy haunikka!
